obj-y += modem.o modem_io_device.o modem_net_flowcontrol_device.o modem_utils.o
obj-$(CONFIG_UMTS_MODEM_XMM6260) += modem_modemctl_device_xmm6260.o
obj-$(CONFIG_LINK_DEVICE_HSIC) += modem_link_device_hsic.o
